name: Test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['stable', 'oldstable', '1.20', '1.19', '1.18']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Test
        run: go test -v ./...
